# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='number_people',
            field=models.IntegerField(default=0, verbose_name='已参加人数'),
        ),
    ]
